xcodebuild_arguments:
    - -scheme
    - InstantSearch
output: docs/reference
# Avoid putting the DocSet within the HTML docs.
# WARNING: The path is relative to the output directory.
docset_path: ../../build/docset
hide_documentation_coverage: true
clean: true
abstract:
    - LICENSE
readme: docgen/jazzy/index.md
custom_categories:
    - name: Core
      children:
        - InstantSearch
    - name: Widgets
      children:
        - ActivityIndicatorWidget
        - DatePickerWidget
        - HitsCollectionWidget
        - OneValueSwitchWidget
        - RefinementCollectionWidget
        - RefinementTableWidget
        - SearchBarWidget
        - SegmentedControlWidget
        - SliderWidget
        - StatsButtonWidget
        - StatsLabelWidget
        - StepperWidget
        - SwitchWidget
        - TextFieldWidget
        - TwoValuesSwitchWidget
    - name: Base ViewController
      children:
        - HitsCollectionViewController
        - HitsTableViewController
        - RefinementCollectionViewController
        - RefinementTableViewController
    - name: Controllers
      children:
        - HitsController
        - RefinementController
    - name: Protocols
      children:
        - AlgoliaWidget
        - HitsCollectionViewDataSource
        - HitsCollectionViewDelegate
        - HitsTableViewDataSource
        - HitsTableViewDelegate
        - RefinableDelegate
        - RefinementCollectionViewDataSource
        - RefinementCollectionViewDelegate
        - RefinementTableViewDataSource
        - RefinementTableViewDelegate
        - ResultingDelegate
        - SearchableViewModel
    - name: Helpers
      children:
        - UILabel
